block_content_revision_ui.settings:
  type: config_object
  label: 'Block Content Revision UI'
  mapping:
    allow_revert_current_revision:
      type: boolean
      label: 'Allow reverting current revision'
