version: "3.5"

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site/web:/var/www/html
      - ./site:/opt/drupal
    ports:
      - 8080:80

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: oregontheater
      MYSQL_USER: oregontheater
      MYSQL_PASSWORD: "cXJdewdchiS"
      MYSQL_ROOT_PASSWORD: "dsf2DhjDFcvWqft"
    ports:
      - 3352:3306
    command: mysqld --max_allowed_packet=32M --lower_case_table_names=1
    volumes:
      - ./database:/var/lib/mysql
      - ./sql-import-files:/docker-entrypoint-initdb.d
