_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  asset_injector: 0
  automated_cron: 0
  background_image_formatter: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity_browser: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  geocoder: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geofield_map: 0
  help: 0
  history: 0
  image: 0
  jsonapi: 0
  jsonapi_image_styles: 0
  jsonapi_page_limit: 0
  leaflet: 0
  leaflet_map_timeline: 0
  leaflet_markercluster: 0
  leaflet_views: 0
  link: 0
  linkit: 0
  menu_ui: 0
  mysql: 0
  node: 0
  node_edit_protection: 0
  optional_end_date: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  verf: 0
  views_data_export: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  corporate_lite: 0
profile: standard
