_core:
  default_config_hash: t48gCU9DzYfjb3bAOIqHLzhL0ChBlXh6_5B5Pyo9t8g
allow_insecure_uploads: false
default_scheme: public
path:
  temporary: sites/oregontheaterproject2-stage.uoregon.edu/private/temp
  private: sites/oregontheaterproject2-stage.uoregon.edu/private/files
temporary_maximum_age: 21600
