<?php

/**
 * @file
 * Hooks written here.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function auditfiles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.auditfiles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Audit Files module allows for comparing and correcting files and file
references in the "files" directory, in the database, and in content. It is
designed to help keep the files on your server in sync with those used by your
Drupal site.') . '</p>';
      $output .= '<p>' . t('This module avoids using the Drupal API when dealing with the files and their
references, so that more or different problems are not created when attempting
to fix the existing ones.') . '</p>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<p>' . t('Go to admin/config/system/auditfiles_config and setting up configuration.') . '</p>';
      return $output;

    default:

  }
}
