filter_settings.filter_image_resize:
  type: filter
  label: 'Filter to resize images'
  mapping:
    image_locations:
      type: mapping
      label: 'image_locations'
      mapping:
        local:
          type: boolean
          label: 'Allow local images.'
        remote:
          type: boolean
          label: 'Allow remote images.'
