eu_cookie_compliance.cookie_category.*:
  type: config_entity
  label: 'Cookie category config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    description:
      type: text
      label: 'Description'
    checkbox_default_state:
      type: string
      label: 'Checkbox default state'
    weight:
      type: integer
      label: 'Weight'
